#!/bin/sh
# Install the grappa rc.d wrappers + enable + start.
#
# Installs:
#   - grappa                    (BEAM release)
#   - grappa-source-alias       (mode-2 privilege wrapper + its prefix scope
#                                rendered from the DB — delegated to
#                                jail_install_source_alias.sh, #646)
#
# Invoke from m42 host:
#   sudo bastille cmd grappa /home/grappa/grappa/infra/freebsd/jail_install_rcd.sh
#
# Idempotent — re-run after `git pull` to refresh the rc.d scripts.

set -eu

REPO_ROOT="/home/grappa/grappa"
ENV_FILE="/usr/local/etc/grappa/grappa.env"

# ── grappa (BEAM release) ──────────────────────────────────────────────
RC_SRC="${REPO_ROOT}/infra/freebsd/rc.d/grappa"
RC_DST="/usr/local/etc/rc.d/grappa"
RC_CONF="/etc/rc.conf.d/grappa"
BEAM_WAIT_SRC="${REPO_ROOT}/infra/freebsd/jail_beam_wait.sh"

echo "[install_rcd] copying ${RC_SRC} -> ${RC_DST}"
install -o root -g wheel -m 0555 "${RC_SRC}" "${RC_DST}"

# The rc.d wrapper runs this helper straight from the checkout, so
# re-assert its exec bit on every install.
# Why: docs/OPERATIONS.md § "The FreeBSD jail rails (infra/freebsd/)".
echo "[install_rcd] chmod +x ${BEAM_WAIT_SRC}"
chmod 0555 "${BEAM_WAIT_SRC}"

if [ ! -f "${RC_CONF}" ]; then
	echo "[install_rcd] writing ${RC_CONF}"
	cat > "${RC_CONF}" <<EOF
# Auto-generated by jail_install_rcd.sh. Edit by hand if you need to
# move the release elsewhere or run as a different user.
grappa_enable="YES"
grappa_user="grappa"
grappa_release_root="${REPO_ROOT}/_build/prod/rel/grappa"
grappa_env_file="${ENV_FILE}"
EOF
	chmod 0644 "${RC_CONF}"
else
	echo "[install_rcd] ${RC_CONF} already exists — leaving in place"
fi

# ── grappa-source-alias (mode-2 privilege wrapper, #543/#609/#610) ──────
#
# deploy.sh calls the sibling directly too (on every path, not just the
# cold one); the duplicate run on a cold deploy is free. Keeping the call
# here is what makes the fresh-jail bootstrap one command.
# Why: docs/OPERATIONS.md § "The FreeBSD jail rails (infra/freebsd/)" (#646).
"${REPO_ROOT}/infra/freebsd/jail_install_source_alias.sh"

# ── status ─────────────────────────────────────────────────────────────
echo "[install_rcd] service grappa status:"
service grappa status || true

echo "[install_rcd] done."
echo "[install_rcd]   start grappa with:                service grappa start"
