#!/bin/sh
# Install the grappa rc.d wrappers + enable + start.
#
# Installs:
#   - grappa                    (BEAM release)
#   - grappa-source-alias       (mode-2 privilege wrapper + its prefix scope,
#                                rendered from the DB — #646)
#
# The grappa_ndp_keepalive service was retired 2026-08-02 (GH #628, the VNET
# jail cutover): the routed-/64 jail has no proxy-NDP neighbour cache to keep
# warm, so this installer no longer copies or enables it. The scripts survive,
# deprecated, at infra/freebsd/ndp_keepalive.{pl,sh} + rc.d/grappa_ndp_keepalive
# — re-add the install block (see the #628 commit) to bring the service back.
#
# Invoke from m42 host:
#   sudo bastille cmd grappa /home/grappa/grappa/infra/freebsd/jail_install_rcd.sh
#
# Idempotent — re-run after `git pull` to refresh the rc.d scripts.

set -eu

REPO_ROOT="/home/grappa/grappa"
ENV_FILE="/usr/local/etc/grappa/grappa.env"

# ── grappa (BEAM release) ──────────────────────────────────────────────
RC_SRC="${REPO_ROOT}/infra/freebsd/rc.d/grappa"
RC_DST="/usr/local/etc/rc.d/grappa"
RC_CONF="/etc/rc.conf.d/grappa"
BEAM_WAIT_SRC="${REPO_ROOT}/infra/freebsd/jail_beam_wait.sh"

echo "[install_rcd] copying ${RC_SRC} -> ${RC_DST}"
install -o root -g wheel -m 0555 "${RC_SRC}" "${RC_DST}"

# The wrapper's stop/start synchronization delegates to this helper
# straight from the repo checkout — a checkout with a lost exec bit
# would silently degrade stop back to async, so re-assert it on every
# install.
echo "[install_rcd] chmod +x ${BEAM_WAIT_SRC}"
chmod 0555 "${BEAM_WAIT_SRC}"

if [ ! -f "${RC_CONF}" ]; then
	echo "[install_rcd] writing ${RC_CONF}"
	cat > "${RC_CONF}" <<EOF
# Auto-generated by jail_install_rcd.sh. Edit by hand if you need to
# move the release elsewhere or run as a different user.
grappa_enable="YES"
grappa_user="grappa"
grappa_release_root="${REPO_ROOT}/_build/prod/rel/grappa"
grappa_env_file="${ENV_FILE}"
EOF
	chmod 0644 "${RC_CONF}"
else
	echo "[install_rcd] ${RC_CONF} already exists — leaving in place"
fi

# grappa_ndp_keepalive is intentionally NOT installed here — deprecated
# 2026-08-02 (GH #628); see the header comment above.

# ── grappa-source-alias (mode-2 privilege wrapper, #543/#609/#610) ──────
#
# #646 — this used to be hand-installed, so the deployed code and the
# installed wrapper drifted in silence: shipping #610 (whose `arm_check` calls
# the new `probe` subcommand) against the pre-#610 wrapper made every probe
# exit 64, disarmed mode 2, and held EVERY static-mapping session in
# production. The wrapper is versioned in the repo and installed outside it,
# exactly like the rc.d script above — so it gets the same treatment, on every
# deploy, instead of a step someone has to remember.
SA_SRC="${REPO_ROOT}/infra/freebsd/bin/grappa-source-alias"
SA_DST="/usr/local/sbin/grappa-source-alias"
SA_CONF="/usr/local/etc/grappa/source-alias.conf"

echo "[install_rcd] copying ${SA_SRC} -> ${SA_DST}"
install -o root -g wheel -m 0555 "${SA_SRC}" "${SA_DST}"

# The wrapper reads its privilege SCOPE — the prefix it may alias inside, and
# refuses to alias outside of — from a root-owned config file, and fails
# closed without it. That prefix MUST equal ServerSettings'
# `addressing.static_mapping_prefix`: a drift does not misbehave quietly, it
# refuses the arm probe with exit 65, i.e. it surfaces as an outage. Render it
# from the DB so the two cannot be kept in sync by hand.
#
# No prefix in the DB (mode 1, or a fresh install) → leave any existing file
# alone rather than truncate it: in that configuration the wrapper is never
# invoked, and a half-written scope is worse than a stale one.
DB_PATH=$(. "${ENV_FILE}" 2>/dev/null; printf '%s' "${DATABASE_PATH:-}")
SA_PREFIX=""

if [ -n "${DB_PATH}" ] && [ -r "${DB_PATH}" ]; then
	SA_PREFIX=$(sqlite3 "file:${DB_PATH}?mode=ro" \
		"select value from server_settings where key='addressing.static_mapping_prefix';" \
		2>/dev/null || true)
fi

if [ -n "${SA_PREFIX}" ]; then
	echo "[install_rcd] rendering ${SA_CONF} (PREFIX=${SA_PREFIX})"
	mkdir -p /usr/local/etc/grappa
	SA_TMP="${SA_CONF}.new.$$"
	printf '# Auto-generated by jail_install_rcd.sh from the DB prefix. Do not edit.\nPREFIX=%s\n' \
		"${SA_PREFIX}" > "${SA_TMP}"
	install -o root -g wheel -m 0444 "${SA_TMP}" "${SA_CONF}"
	rm -f "${SA_TMP}"
else
	echo "[install_rcd] no static_mapping_prefix in the DB — leaving ${SA_CONF} as-is"
fi

# ── status ─────────────────────────────────────────────────────────────
echo "[install_rcd] service grappa status:"
service grappa status || true

echo "[install_rcd] done."
echo "[install_rcd]   start grappa with:                service grappa start"
