#!/bin/sh
# Install the grappa-source-alias privilege wrapper (#543/#609/#610) and
# render its prefix scope from the DB.
#
# Runs as ROOT inside the jail. Idempotent by construction — a copy, a
# chmod and a rendered config file — which is what lets the deploy run it
# on EVERY path, hot AND cold, rather than only on a restart. The
# installed artifacts are a function of the checkout + the DB, not of any
# file-based deploy classification.
# Why: docs/OPERATIONS.md § "The FreeBSD jail rails (infra/freebsd/)" (#646).
#
# Invoke by hand (fresh jail, or after editing the wrapper in place):
#   sudo bastille cmd grappa /home/grappa/grappa/infra/freebsd/jail_install_source_alias.sh

set -eu

REPO_ROOT="${REPO_ROOT:-/home/grappa/grappa}"
ENV_FILE="${ENV_FILE:-/usr/local/etc/grappa/grappa.env}"

SA_SRC="${REPO_ROOT}/infra/freebsd/bin/grappa-source-alias"
SA_DST="${SA_DST:-/usr/local/sbin/grappa-source-alias}"
SA_CONF="${SA_CONF:-/usr/local/etc/grappa/source-alias.conf}"

echo "[install_source_alias] copying ${SA_SRC} -> ${SA_DST}"
install -o root -g wheel -m 0555 "${SA_SRC}" "${SA_DST}"

# The wrapper reads its privilege SCOPE — the prefix it may alias inside,
# and refuses to alias outside of — from this root-owned config file, and
# fails closed without it. Render it from the DB so it cannot drift from
# ServerSettings' `addressing.static_mapping_prefix`; with no prefix in
# the DB, leave any existing file alone rather than truncate it.
# Why: docs/OPERATIONS.md § "The FreeBSD jail rails (infra/freebsd/)".
# shellcheck source=/dev/null  # runtime env file, not in the repo
DB_PATH=$(. "${ENV_FILE}" 2>/dev/null; printf '%s' "${DATABASE_PATH:-}")
SA_PREFIX=""

if [ -n "${DB_PATH}" ] && [ -r "${DB_PATH}" ]; then
	SA_PREFIX=$(sqlite3 "file:${DB_PATH}?mode=ro" \
		"select value from server_settings where key='addressing.static_mapping_prefix';" \
		2>/dev/null || true)
fi

if [ -n "${SA_PREFIX}" ]; then
	echo "[install_source_alias] rendering ${SA_CONF} (PREFIX=${SA_PREFIX})"
	mkdir -p "$(dirname "${SA_CONF}")"
	SA_TMP="${SA_CONF}.new.$$"
	printf '# Auto-generated by jail_install_source_alias.sh from the DB prefix. Do not edit.\nPREFIX=%s\n' \
		"${SA_PREFIX}" > "${SA_TMP}"
	install -o root -g wheel -m 0444 "${SA_TMP}" "${SA_CONF}"
	rm -f "${SA_TMP}"
else
	echo "[install_source_alias] no static_mapping_prefix in the DB — leaving ${SA_CONF} as-is"
fi
