defmodule Grappa.ReleaseCLIInstallTest do
  @moduledoc """
  #1158 — the `mix release` step that puts the operator CLI on
  `bin/grappa`.

  The step is the only reason the account verbs exist on a packaged box,
  and it is the one piece of this door that a normal test run never
  executes: assembling a release takes a prod build. So it is driven here
  against a temp tree that looks like one, which is enough — the step's
  whole job is a rename, a copy and a refusal.

  The refusal is the part that most wants a test. If `:assemble` ever
  stops regenerating the boot script, renaming would move the DISPATCHER
  to `grappa-release`, and the dispatcher would then exec itself: an
  infinite loop on the very first `bin/grappa daemon`, i.e. on every
  substrate's boot at once, discovered in production.
  """
  use ExUnit.Case, async: true

  @cli_source "infra/release/grappa.sh"
  @external_resource @cli_source

  @generated "#!/bin/sh\n# generated by mix release\ncase $1 in start) ;; esac\n"

  setup do
    root = Path.join(System.tmp_dir!(), "grappa-rel-#{System.unique_integer([:positive])}")
    File.mkdir_p!(Path.join(root, "bin"))
    File.write!(Path.join(root, "bin/grappa"), @generated)
    on_exit(fn -> File.rm_rf!(root) end)

    %{root: root, release: struct(Mix.Release, name: :grappa, path: root)}
  end

  defp read(root, name), do: File.read!(Path.join([root, "bin", name]))

  test "the dispatcher takes over bin/grappa and the boot script moves aside", %{
    root: root,
    release: release
  } do
    assert %Mix.Release{} = Grappa.MixProject.install_operator_cli(release)

    assert read(root, "grappa") == File.read!(@cli_source)
    assert read(root, "grappa-release") == @generated
  end

  test "the dispatcher is executable — a release ships it, nobody chmods it later", %{
    root: root,
    release: release
  } do
    Grappa.MixProject.install_operator_cli(release)

    %File.Stat{mode: mode} = File.stat!(Path.join([root, "bin", "grappa"]))
    assert Bitwise.band(mode, 0o111) == 0o111
  end

  test "a second pass refuses instead of renaming the dispatcher onto itself", %{
    root: root,
    release: release
  } do
    Grappa.MixProject.install_operator_cli(release)

    assert_raise Mix.Error, ~r/already the dispatcher/, fn ->
      Grappa.MixProject.install_operator_cli(release)
    end

    # And the refusal happened BEFORE any move: the real boot script is
    # still where the dispatcher will exec it.
    assert read(root, "grappa-release") == @generated
  end

  test "the step is wired into the release's steps" do
    # The behaviour above is worth nothing if no release ever calls it.
    # Read, not assumed: `steps:` is a list of captures in mix.exs and
    # nothing else links the function to the build.
    assert File.read!("mix.exs") =~ "&__MODULE__.install_operator_cli/1"
  end
end
